// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Farm.Models;

#nullable disable

namespace Smart_Farm.Migrations
{
    [DbContext(typeof(farContext))]
    [Migration("20260426000351_newAddPlantStageAndIrrigationTemplate")]
    partial class newAddPlantStageAndIrrigationTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CROP_FERTILIZER", b =>
                {
                    b.Property<int>("FrId")
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.HasKey("FrId", "Cid")
                        .HasName("PK__CROP_FER__3EAB9A937EDA9D18");

                    b.HasIndex("Cid");

                    b.ToTable("CROP_FERTILIZER", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Smart_Farm.Models.AI_Diagnosis", b =>
                {
                    b.Property<int>("ADid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ADid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date");

                    b.Property<int?>("Did")
                        .HasColumnType("int");

                    b.Property<string>("GeminiArabicReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("plant_image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ADid")
                        .HasName("PK__AI_Diagn__7931D1B8DEB8ED6F");

                    b.HasIndex("Cid");

                    b.HasIndex("Did");

                    b.ToTable("AI_Diagnosis");
                });

            modelBuilder.Entity("Smart_Farm.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DomainUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Smart_Farm.Models.COMPATIBILITY", b =>
                {
                    b.Property<int>("FrId")
                        .HasColumnType("int");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("FrId", "Pid")
                        .HasName("PK__COMPATIB__AEE362867FBB5969");

                    b.HasIndex("Pid");

                    b.ToTable("COMPATIBILITY");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cid"));

                    b.Property<decimal?>("Area_size")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Current_Stage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<string>("Soil_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Start_date")
                        .HasColumnType("date");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Cid")
                        .HasName("PK__CROP__C1FFD8616FF697CD");

                    b.HasIndex("Pid");

                    b.HasIndex("Uid");

                    b.ToTable("CROP");
                });

            modelBuilder.Entity("Smart_Farm.Models.Disease", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nause")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Did")
                        .HasName("PK__Disease__C03122188275DDE5");

                    b.ToTable("Disease");
                });

            modelBuilder.Entity("Smart_Farm.Models.FERTILIZER", b =>
                {
                    b.Property<int>("FrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Fertilizer_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FrId")
                        .HasName("PK__FERTILIZ__32B46715A38ED2B3");

                    b.ToTable("FERTILIZER");
                });

            modelBuilder.Entity("Smart_Farm.Models.GROWS_IN", b =>
                {
                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<string>("Plant_in_season_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Pid", "Sid")
                        .HasName("PK__GROWS_IN__59D1BCEFD9462B22");

                    b.HasIndex("Sid");

                    b.ToTable("GROWS_IN");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency_unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Frequency_value")
                        .HasColumnType("int");

                    b.Property<string>("Irrigation_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PTid")
                        .HasColumnType("int");

                    b.Property<int?>("Sis")
                        .HasColumnType("int");

                    b.Property<decimal?>("Water_amount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Iid")
                        .HasName("PK__IRRIGATI__C4962F8429AE39D0");

                    b.HasIndex("Cid");

                    b.HasIndex("PTid");

                    b.HasIndex("Sis");

                    b.ToTable("IRRIGATION");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration_days")
                        .HasColumnType("int");

                    b.Property<string>("Name_stage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PSid")
                        .HasColumnType("int");

                    b.Property<int?>("Stage_order")
                        .HasColumnType("int");

                    b.HasKey("Sid")
                        .HasName("PK__IRRIGATI__CA1E5D78AA21B4A3");

                    b.HasIndex("Cid");

                    b.HasIndex("PSid");

                    b.ToTable("IRRIGATION_STAGE");
                });

            modelBuilder.Entity("Smart_Farm.Models.ORDER", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Oid"));

                    b.Property<decimal?>("Discount_amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Order_date")
                        .HasColumnType("date");

                    b.Property<string>("Order_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<string>("Promo_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Total_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Oid")
                        .HasName("PK__ORDERS__CB3E4F31B009E3AD");

                    b.HasIndex("Pid");

                    b.HasIndex("Uid");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<int?>("Days_to_harvest")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fertilizer_need")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Humidity_range")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Seed_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soil_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperature_range")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Water_need")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Pid")
                        .HasName("PK__PLANT__C5705938049F0DBC");

                    b.ToTable("PLANT");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_IRRIGATION_TEMPLATE", b =>
                {
                    b.Property<int>("PTid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PTid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency_unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Frequency_value")
                        .HasColumnType("int");

                    b.Property<string>("Irrigation_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PSid")
                        .HasColumnType("int");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<decimal?>("Water_amount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PTid");

                    b.HasIndex("PSid");

                    b.HasIndex("Pid");

                    b.ToTable("PLANT_IRRIGATION_TEMPLATE");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_STAGE", b =>
                {
                    b.Property<int>("PSid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PSid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration_days")
                        .HasColumnType("int");

                    b.Property<string>("Name_stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<int?>("Stage_order")
                        .HasColumnType("int");

                    b.HasKey("PSid");

                    b.HasIndex("Pid");

                    b.ToTable("PLANT_STAGE");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<DateOnly?>("Added_date")
                        .HasColumnType("date");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Pid")
                        .HasName("PK__PRODUCT__C5705938F6FC9017");

                    b.HasIndex("Cid");

                    b.HasIndex("Uid");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("Smart_Farm.Models.REVIEW", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Rid");

                    b.HasIndex("Pid");

                    b.HasIndex("Uid");

                    b.ToTable("REVIEW");
                });

            modelBuilder.Entity("Smart_Farm.Models.SEASON", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Sid")
                        .HasName("PK__SEASON__CA1E5D786783D710");

                    b.ToTable("SEASON");
                });

            modelBuilder.Entity("Smart_Farm.Models.Task", b =>
                {
                    b.Property<int>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Task_id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Task_id")
                        .HasName("PK__Task__716846B5F30205F9");

                    b.HasIndex("Uid");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Address_line")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("First_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("PasswordHashed")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Uid")
                        .HasName("PK__USERS__C5B69A4A9CA97C86");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER_PHONE", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Phone", "Uid")
                        .HasName("PK__USER_PHO__E0255C3B7CD4D930");

                    b.HasIndex("Uid");

                    b.ToTable("USER_PHONE");
                });

            modelBuilder.Entity("CROP_FERTILIZER", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", null)
                        .WithMany()
                        .HasForeignKey("Cid")
                        .IsRequired()
                        .HasConstraintName("FK__CROP_FERTIL__Cid__5812160E");

                    b.HasOne("Smart_Farm.Models.FERTILIZER", null)
                        .WithMany()
                        .HasForeignKey("FrId")
                        .IsRequired()
                        .HasConstraintName("FK__CROP_FERTI__FrId__571DF1D5");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Smart_Farm.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Smart_Farm.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Farm.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Smart_Farm.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Smart_Farm.Models.AI_Diagnosis", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("AI_Diagnoses")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__AI_Diagnosi__Cid__6754599E");

                    b.HasOne("Smart_Farm.Models.Disease", "DidNavigation")
                        .WithMany("AI_Diagnoses")
                        .HasForeignKey("Did")
                        .HasConstraintName("FK__AI_Diagnosi__Did__68487DD7");

                    b.Navigation("CidNavigation");

                    b.Navigation("DidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.COMPATIBILITY", b =>
                {
                    b.HasOne("Smart_Farm.Models.FERTILIZER", "Fr")
                        .WithMany("COMPATIBILITies")
                        .HasForeignKey("FrId")
                        .IsRequired()
                        .HasConstraintName("FK__COMPATIBIL__FrId__5AEE82B9");

                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("COMPATIBILITies")
                        .HasForeignKey("Pid")
                        .IsRequired()
                        .HasConstraintName("FK__COMPATIBILI__Pid__5BE2A6F2");

                    b.Navigation("Fr");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("CROPs")
                        .HasForeignKey("Pid");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("CROPs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__CROP__Uid__4316F928");

                    b.Navigation("PidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.GROWS_IN", b =>
                {
                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("GROWS_INs")
                        .HasForeignKey("Pid")
                        .IsRequired()
                        .HasConstraintName("FK__GROWS_IN__Pid__5165187F");

                    b.HasOne("Smart_Farm.Models.SEASON", "SidNavigation")
                        .WithMany("GROWS_INs")
                        .HasForeignKey("Sid")
                        .IsRequired()
                        .HasConstraintName("FK__GROWS_IN__Sid__52593CB8");

                    b.Navigation("PidNavigation");

                    b.Navigation("SidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("IRRIGATIONs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__IRRIGATION__Cid__628FA481");

                    b.HasOne("Smart_Farm.Models.PLANT_IRRIGATION_TEMPLATE", "PTidNavigation")
                        .WithMany("IRRIGATIONs")
                        .HasForeignKey("PTid");

                    b.HasOne("Smart_Farm.Models.IRRIGATION_STAGE", "SisNavigation")
                        .WithMany("IRRIGATIONs")
                        .HasForeignKey("Sis")
                        .HasConstraintName("FK__IRRIGATION__Sis__619B8048");

                    b.Navigation("CidNavigation");

                    b.Navigation("PTidNavigation");

                    b.Navigation("SisNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("IRRIGATION_STAGEs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__IRRIGATION___Cid__5EBF139D");

                    b.HasOne("Smart_Farm.Models.PLANT_STAGE", "PSidNavigation")
                        .WithMany("IRRIGATION_STAGEs")
                        .HasForeignKey("PSid");

                    b.Navigation("CidNavigation");

                    b.Navigation("PSidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.ORDER", b =>
                {
                    b.HasOne("Smart_Farm.Models.PRODUCT", "PidNavigation")
                        .WithMany("ORDERs")
                        .HasForeignKey("Pid")
                        .HasConstraintName("FK__ORDERS__Pid__49C3F6B7");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("ORDERs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__ORDERS__Uid__4AB81AF0");

                    b.Navigation("PidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_IRRIGATION_TEMPLATE", b =>
                {
                    b.HasOne("Smart_Farm.Models.PLANT_STAGE", "PSidNavigation")
                        .WithMany("PLANT_IRRIGATION_TEMPLATEs")
                        .HasForeignKey("PSid");

                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("PLANT_IRRIGATION_TEMPLATEs")
                        .HasForeignKey("Pid");

                    b.Navigation("PSidNavigation");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_STAGE", b =>
                {
                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("PLANT_STAGEs")
                        .HasForeignKey("Pid");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("PRODUCTs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__PRODUCT__Cid__46E78A0C");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("PRODUCTs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__PRODUCT__Uid__45F365D3");

                    b.Navigation("CidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.REVIEW", b =>
                {
                    b.HasOne("Smart_Farm.Models.PRODUCT", "PidNavigation")
                        .WithMany()
                        .HasForeignKey("Pid");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany()
                        .HasForeignKey("Uid");

                    b.Navigation("PidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.Task", b =>
                {
                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__Task__Uid__3C69FB99");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER_PHONE", b =>
                {
                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("USER_PHONEs")
                        .HasForeignKey("Uid")
                        .IsRequired()
                        .HasConstraintName("FK__USER_PHONE__Uid__398D8EEE");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.Navigation("AI_Diagnoses");

                    b.Navigation("IRRIGATION_STAGEs");

                    b.Navigation("IRRIGATIONs");

                    b.Navigation("PRODUCTs");
                });

            modelBuilder.Entity("Smart_Farm.Models.Disease", b =>
                {
                    b.Navigation("AI_Diagnoses");
                });

            modelBuilder.Entity("Smart_Farm.Models.FERTILIZER", b =>
                {
                    b.Navigation("COMPATIBILITies");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.Navigation("IRRIGATIONs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT", b =>
                {
                    b.Navigation("COMPATIBILITies");

                    b.Navigation("CROPs");

                    b.Navigation("GROWS_INs");

                    b.Navigation("PLANT_IRRIGATION_TEMPLATEs");

                    b.Navigation("PLANT_STAGEs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_IRRIGATION_TEMPLATE", b =>
                {
                    b.Navigation("IRRIGATIONs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT_STAGE", b =>
                {
                    b.Navigation("IRRIGATION_STAGEs");

                    b.Navigation("PLANT_IRRIGATION_TEMPLATEs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.Navigation("ORDERs");
                });

            modelBuilder.Entity("Smart_Farm.Models.SEASON", b =>
                {
                    b.Navigation("GROWS_INs");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER", b =>
                {
                    b.Navigation("CROPs");

                    b.Navigation("ORDERs");

                    b.Navigation("PRODUCTs");

                    b.Navigation("Tasks");

                    b.Navigation("USER_PHONEs");
                });
#pragma warning restore 612, 618
        }
    }
}
