// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("AI_Diagnosis")]
public partial class AI_Diagnosis
{
    [Key]
    public int ADid { get; set; }
    public DateOnly? DiagnosisDate { get; set; }
    [StringLength(100)]
    public string Result { get; set; }
    public int? Did { get; set; }
    public int? Cid { get; set; }
    [Column(TypeName = "nvarchar(max)")] 
    public string plant_image { get; set; }
    [Column(TypeName = "nvarchar(max)")]
    public string GeminiArabicReport { get; set; }
    [ForeignKey("Cid")]
    [InverseProperty("AI_Diagnoses")]
    public virtual CROP CidNavigation { get; set; }
    [ForeignKey("Did")]
    [InverseProperty("AI_Diagnoses")]
    public virtual Disease DidNavigation { get; set; }
}