// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Smart_Farm.DTOS;

namespace Smart_Farm.Models;

[Table("AI_Diagnosis")]
public partial class AI_Diagnosis
{
    [Key]
    public int ADid { get; set; }
    public DateTime? DiagnosisDate { get; set; }
    public double? Confidence { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Result { get; set; }

    public int? Did { get; set; }
    public int? Cid { get; set; }
    public int? FarmId { get; set; }    
    public int? UserId { get; set; }   
    public int? Pid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string plant_image { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string? GrogArabicReport { get; set; }

    [ForeignKey("Cid")]
    [InverseProperty("AI_Diagnoses")]
    public virtual CROP CidNavigation { get; set; }

    [ForeignKey("Did")]
    [InverseProperty("AI_Diagnoses")]
    public virtual Disease DidNavigation { get; set; }
}
