// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("CROP")]
public partial class CROP
{
    [Key]
    public int Cid { get; set; }

    public int? Pid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Notes { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Area_size { get; set; }

    public DateOnly? Start_date { get; set; }

    [StringLength(100)]
    public string Soil_type { get; set; }

    [StringLength(100)]
    public string Current_Stage { get; set; }

    public int? Uid { get; set; }

    [InverseProperty("CidNavigation")]
    public virtual ICollection<AI_Diagnosis> AI_Diagnoses { get; set; } = new List<AI_Diagnosis>();

    [InverseProperty("CidNavigation")]
    public virtual ICollection<IRRIGATION_STAGE> IRRIGATION_STAGEs { get; set; } = new List<IRRIGATION_STAGE>();

    [InverseProperty("CidNavigation")]
    public virtual ICollection<IRRIGATION> IRRIGATIONs { get; set; } = new List<IRRIGATION>();

    [InverseProperty("CidNavigation")]
    public virtual ICollection<PRODUCT> PRODUCTs { get; set; } = new List<PRODUCT>();

    [ForeignKey("Uid")]
    [InverseProperty("CROPs")]
    public virtual USER UidNavigation { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("CROPs")]
    public virtual PLANT PidNavigation { get; set; }

    [ForeignKey("Cid")]
    [InverseProperty("Cids")]
    public virtual ICollection<FERTILIZER> Frs { get; set; } = new List<FERTILIZER>();
}