// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

public partial class farContext : IdentityDbContext<AppUser, IdentityRole<int>, int>
{
    public farContext()
    {
    }

    public farContext(DbContextOptions<farContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AI_Diagnosis> AI_Diagnoses { get; set; }

    public virtual DbSet<COMPATIBILITY> COMPATIBILITies { get; set; }

    public virtual DbSet<CROP> CROPs { get; set; }

    public virtual DbSet<Disease> Diseases { get; set; }

    public virtual DbSet<FERTILIZER> FERTILIZERs { get; set; }

    public virtual DbSet<GROWS_IN> GROWS_INs { get; set; }

    public virtual DbSet<IRRIGATION> IRRIGATIONs { get; set; }

    public virtual DbSet<IRRIGATION_STAGE> IRRIGATION_STAGEs { get; set; }

    public virtual DbSet<ORDER> ORDERs { get; set; }

    public virtual DbSet<PLANT> PLANTs { get; set; }

    public virtual DbSet<PRODUCT> PRODUCTs { get; set; }

    public virtual DbSet<PRODUCT_IMAGE> PRODUCT_IMAGEs { get; set; }

    public virtual DbSet<REVIEW> REVIEWs { get; set; }

    public virtual DbSet<SEASON> SEASONs { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<USER> USERs { get; set; }

    public virtual DbSet<USER_PHONE> USER_PHONEs { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Smart_Farm;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.Property(e => e.DomainUserId);
        });

        modelBuilder.Entity<AI_Diagnosis>(entity =>
        {
            entity.HasKey(e => e.ADid).HasName("PK__AI_Diagn__7931D1B8DEB8ED6F");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.AI_Diagnoses).HasConstraintName("FK__AI_Diagnosi__Cid__6754599E");

            entity.HasOne(d => d.DidNavigation).WithMany(p => p.AI_Diagnoses).HasConstraintName("FK__AI_Diagnosi__Did__68487DD7");
        });

        modelBuilder.Entity<COMPATIBILITY>(entity =>
        {
            entity.HasKey(e => new { e.FrId, e.Pid }).HasName("PK__COMPATIB__AEE362867FBB5969");

            entity.HasOne(d => d.Fr).WithMany(p => p.COMPATIBILITies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__COMPATIBIL__FrId__5AEE82B9");

            entity.HasOne(d => d.PidNavigation).WithMany(p => p.COMPATIBILITies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__COMPATIBILI__Pid__5BE2A6F2");
        });

        modelBuilder.Entity<CROP>(entity =>
        {
            entity.HasKey(e => e.Cid).HasName("PK__CROP__C1FFD8616FF697CD");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.CROPs).HasConstraintName("FK__CROP__Uid__4316F928");
        });

        modelBuilder.Entity<Disease>(entity =>
        {
            entity.HasKey(e => e.Did).HasName("PK__Disease__C03122188275DDE5");
        });

        modelBuilder.Entity<FERTILIZER>(entity =>
        {
            entity.HasKey(e => e.FrId).HasName("PK__FERTILIZ__32B46715A38ED2B3");

            entity.HasMany(d => d.Cids).WithMany(p => p.Frs)
                .UsingEntity<Dictionary<string, object>>(
                    "CROP_FERTILIZER",
                    r => r.HasOne<CROP>().WithMany()
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__CROP_FERTIL__Cid__5812160E"),
                    l => l.HasOne<FERTILIZER>().WithMany()
                        .HasForeignKey("FrId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__CROP_FERTI__FrId__571DF1D5"),
                    j =>
                    {
                        j.HasKey("FrId", "Cid").HasName("PK__CROP_FER__3EAB9A937EDA9D18");
                        j.ToTable("CROP_FERTILIZER");
                    });
        });

        modelBuilder.Entity<GROWS_IN>(entity =>
        {
            entity.HasKey(e => new { e.Pid, e.Sid }).HasName("PK__GROWS_IN__59D1BCEFD9462B22");

            entity.HasOne(d => d.PidNavigation).WithMany(p => p.GROWS_INs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GROWS_IN__Pid__5165187F");

            entity.HasOne(d => d.SidNavigation).WithMany(p => p.GROWS_INs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GROWS_IN__Sid__52593CB8");
        });

        modelBuilder.Entity<IRRIGATION>(entity =>
        {
            entity.HasKey(e => e.Iid).HasName("PK__IRRIGATI__C4962F8429AE39D0");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.IRRIGATIONs).HasConstraintName("FK__IRRIGATION__Cid__628FA481");

            entity.HasOne(d => d.SisNavigation).WithMany(p => p.IRRIGATIONs).HasConstraintName("FK__IRRIGATION__Sis__619B8048");
        });

        modelBuilder.Entity<IRRIGATION_STAGE>(entity =>
        {
            entity.HasKey(e => e.Sid).HasName("PK__IRRIGATI__CA1E5D78AA21B4A3");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.IRRIGATION_STAGEs).HasConstraintName("FK__IRRIGATION___Cid__5EBF139D");
        });

        modelBuilder.Entity<ORDER>(entity =>
        {
            entity.HasKey(e => e.Oid).HasName("PK__ORDERS__CB3E4F31B009E3AD");

            entity.HasOne(d => d.PidNavigation).WithMany(p => p.ORDERs).HasConstraintName("FK__ORDERS__Pid__49C3F6B7");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.ORDERs).HasConstraintName("FK__ORDERS__Uid__4AB81AF0");
        });

        modelBuilder.Entity<PLANT>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__PLANT__C5705938049F0DBC");
        });

        modelBuilder.Entity<PRODUCT>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__PRODUCT__C5705938F6FC9017");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.PRODUCTs).HasConstraintName("FK__PRODUCT__Cid__46E78A0C");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.PRODUCTs).HasConstraintName("FK__PRODUCT__Uid__45F365D3");
        });

        modelBuilder.Entity<SEASON>(entity =>
        {
            entity.HasKey(e => e.Sid).HasName("PK__SEASON__CA1E5D786783D710");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Task_id).HasName("PK__Task__716846B5F30205F9");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.Tasks).HasConstraintName("FK__Task__Uid__3C69FB99");
        });

        modelBuilder.Entity<USER>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__USERS__C5B69A4A9CA97C86");
        });

        modelBuilder.Entity<USER_PHONE>(entity =>
        {
            entity.HasKey(e => new { e.Phone, e.Uid }).HasName("PK__USER_PHO__E0255C3B7CD4D930");

            entity.HasOne(d => d.UidNavigation).WithMany(p => p.USER_PHONEs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__USER_PHONE__Uid__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}