// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("IRRIGATION_STAGE")]
public partial class IRRIGATION_STAGE
{
    [Key]
    public int Sid { get; set; }

    [StringLength(100)]
    public string Name_stage { get; set; }

    public int? Stage_order { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    public int? Cid { get; set; }

    [ForeignKey("Cid")]
    [InverseProperty("IRRIGATION_STAGEs")]
    public virtual CROP CidNavigation { get; set; }

    [InverseProperty("SisNavigation")]
    public virtual ICollection<IRRIGATION> IRRIGATIONs { get; set; } = new List<IRRIGATION>();
    public int? PSid { get; set; }
    public int? Duration_days { get; set; }

    [ForeignKey("PSid")]
    public virtual PLANT_STAGE PSidNavigation { get; set; }
}