// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("IRRIGATION")]
public partial class IRRIGATION
{
    [Key]
    public int Iid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    [StringLength(20)]
    public string Frequency_unit { get; set; }

    public int? Frequency_value { get; set; }

    [StringLength(100)]
    public string Irrigation_name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Water_amount { get; set; }

    public int? Sis { get; set; }

    public int? Cid { get; set; }

    [ForeignKey("Cid")]
    [InverseProperty("IRRIGATIONs")]
    public virtual CROP CidNavigation { get; set; }

    [ForeignKey("Sis")]
    [InverseProperty("IRRIGATIONs")]
    public virtual IRRIGATION_STAGE SisNavigation { get; set; }
    public int? PTid { get; set; }

    [ForeignKey("PTid")]
    public virtual PLANT_IRRIGATION_TEMPLATE PTidNavigation { get; set; }
}