// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("PLANT")]
public partial class PLANT
{
    [Key]
    public int Pid { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    [StringLength(100)]
    public string Seed_type { get; set; }

    [StringLength(100)]
    public string Fertilizer_need { get; set; }

    public int? Days_to_harvest { get; set; }

    [StringLength(50)]
    public string Season { get; set; }

    [StringLength(50)]
    public string Humidity_range { get; set; }

    [StringLength(50)]
    public string Water_need { get; set; }

    [StringLength(50)]
    public string Soil_type { get; set; }

    [StringLength(50)]
    public string Temperature_range { get; set; }

    [InverseProperty("PidNavigation")]
    public virtual ICollection<COMPATIBILITY> COMPATIBILITies { get; set; } = new List<COMPATIBILITY>();

    [InverseProperty("PidNavigation")]
    public virtual ICollection<GROWS_IN> GROWS_INs { get; set; } = new List<GROWS_IN>();

    [InverseProperty("PidNavigation")]
    public virtual ICollection<CROP> CROPs { get; set; } = new List<CROP>();
}