// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("USERS")]
public partial class USER
{
    [Key]
    public int Uid { get; set; }

    [StringLength(50)]
    public string First_name { get; set; }

    [StringLength(50)]
    public string Last_name { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Address_line { get; set; }

    [StringLength(100)]
    public string City_name { get; set; }

    [Column(TypeName = "decimal(10, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(10, 6)")]
    public decimal? Longitude { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [StringLength(64)]
    public string PasswordHashed { get; set; }

    [InverseProperty("UidNavigation")]
    public virtual ICollection<CROP> CROPs { get; set; } = new List<CROP>();

    [InverseProperty("UidNavigation")]
    public virtual ICollection<ORDER> ORDERs { get; set; } = new List<ORDER>();

    [InverseProperty("UidNavigation")]
    public virtual ICollection<PRODUCT> PRODUCTs { get; set; } = new List<PRODUCT>();

    [InverseProperty("UidNavigation")]
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    [InverseProperty("UidNavigation")]
    public virtual ICollection<USER_PHONE> USER_PHONEs { get; set; } = new List<USER_PHONE>();
    [Column(TypeName = "nvarchar(max)")]
    public string PhotoUrl { get; set; }

}